In [1]:
%matplotlib inline

In [3]:
# Dependencies
import os
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [6]:
# Load the file
census_data = "../sdhousing_csv.csv"

# Read in the file with Pandas
census_data_df = pd.read_csv(census_data)

# Display the data table for preview
census_data_df.head()

,zip,GEO_NAME,pop_2011,pop_2014,pop_2017,med_hh_inc_11,med_hh_inc_14,med_hh_inc_17,total_units_11,total_units_14,...,ownocc_units_17,rent_units_11,rent_units_14,rent_units_17,med_home_value_11,med_home_value_14,med_home_value_17,median_gross_rent_11,median_gross_rent_14,median_gross_rent_17
0,91901,Alpine California,16606,18184,18238,77064,81379,90397,16104,17782,...,13642,4845,4939,4171,553800,471800,525700,1274,1284,1397
1,91902,Bonita California,17399,19504,19762,78187,88926,92759,17379,19456,...,13997,3187,4447,5702,547200,517700,607100,1462,1653,1777
2,91910,Chula Vista California,71887,76797,76250,56510,54640,59371,71070,75863,...,36004,32504,38753,39141,391800,348300,424700,1137,1189,1298
3,91911,Chula Vista California,79518,83710,84025,48386,48891,52274,79101,83057,...,42151,36788,41399,40945,335700,300100,361600,1154,1210,1359
4,91913,Chula Vista California,40633,43655,49346,89737,84741,87440,40633,43650,...,35928,11542,11786,13409,439800,400300,451700,1831,1823,1947

In [ ]:
# Calculate the